name: kassim
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  eva_icons_flutter: ^2.0.1
  flutter_screenutil: ^3.1.1
  flutter_slidable: ^0.5.7
  intl: ^0.17.0
  path_provider: any
  shared_preferences: null
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
  fonts:
    - family: cairo
      fonts:
        - asset: fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: fonts/Cairo-Light.ttf
          weight: 300
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
        - asset: fonts/Cairo-Black.ttf
          weight: 900

    - family: brlns
      fonts:
        - asset: fonts/BRLNSR.TTF
          weight: 400
        - asset: fonts/BRLNSDB.TTF
          weight: 600
        - asset: fonts/BRLNSB.TTF
          weight: 700

    - family: hpSimplified
      fonts:
        - asset: fonts/HPSimplified_It.ttf
          style: italic
        - asset: fonts/HPSimplified_Rg.ttf
          weight: 400
        - asset: fonts/HPSimplified_Lt.ttf
          weight: 300
        - asset: fonts/HPSimplified_LtIt.ttf
          weight: 300
          style: italic
        - asset: fonts/HPSimplified_Bd.ttf
          weight: 700
        - asset: fonts/HPSimplified_BdIt.ttf
          weight: 700
          style: italic
